<?php
/**
 * Register ACF fields
 *
 * Registers fields for use by the
 * Advanced Custom Fields Pro plugin.
 *
 * @package    WordPress/ClassicPress
 * @subpackage AFFP_Theme
 * @since      1.0.0
 */

namespace AFFP_Theme\Includes;

// Restrict direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group( [
		'key'    => 'group_5e456c5f2f4d3',
		'title'  => __( 'Front Page', 'affp-theme' ),
		'fields' => [
			[
				'key'               => 'field_5e4597040f55b',
				'label'             => __( 'Intro', 'affp-theme' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => __( '', 'affp-theme' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'placement'         => 'top',
				'endpoint'          => 0,
				'icon_class'        => '',
				'show_icon_only'    => 0,
			],
			[
				'key'               => 'field_5e45978bf996a',
				'label'             => __( 'Title', 'affp-theme' ),
				'name'              => 'intro_section_title',
				'type'              => 'text',
				'instructions'      => __( 'Defaults to the site title in Settings > General.', 'affp-theme' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '',
				'placeholder'       => __( '', 'affp-theme' ),
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			],
			[
				'key'               => 'field_5e45979ff996b',
				'label'             => __( 'Tagline/Description', 'affp-theme' ),
				'name'              => 'intro_section_tagline',
				'type'              => 'text',
				'instructions'      => __( 'Defaults to the tagline in Settings > General.', 'affp-theme' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '',
				'placeholder'       => __( '', 'affp-theme' ),
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			],
			[
				'key'               => 'field_5e4597150f55c',
				'label'             => __( 'Background Images', 'affp-theme' ),
				'name'              => 'intro_section_images',
				'type'              => 'gallery',
				'instructions'      => __( 'If only one image is selected it will display static. If two or more images are selected then they will display as a slideshow. Minimum 1280 pixels wide by 720 pixels high (HD video aspect ratio).', 'affp-theme' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'return_format'     => 'array',
				'preview_size'      => 'medium',
				'insert'            => 'append',
				'library'           => 'all',
				'min'               => '',
				'max'               => '',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => 'jpg',
			],
			[
				'key'               => 'field_5e4599435bc2e',
				'label'             => __( 'Sections', 'affp-theme' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => __( '', 'affp-theme' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'placement'         => 'top',
				'endpoint'          => 0,
				'icon_class'        => '',
				'show_icon_only'    => 0,
			],
			[
				'acfe_flexible_advanced'             => 0,
				'acfe_flexible_stylised_button'      => 0,
				'acfe_flexible_hide_empty_message'   => 0,
				'acfe_flexible_empty_message'        => '',
				'acfe_flexible_disable_ajax_title'   => 0,
				'acfe_flexible_layouts_thumbnails'   => 0,
				'acfe_flexible_layouts_settings'     => 0,
				'acfe_flexible_layouts_ajax'         => 0,
				'acfe_flexible_layouts_templates'    => 0,
				'acfe_flexible_layouts_previews'     => 0,
				'acfe_flexible_layouts_placeholder'  => 0,
				'acfe_flexible_title_edition'        => 0,
				'acfe_flexible_clone'                => 0,
				'acfe_flexible_copy_paste'           => 0,
				'acfe_flexible_close_button'         => 0,
				'acfe_flexible_remove_add_button'    => 0,
				'acfe_flexible_remove_delete_button' => 0,
				'acfe_flexible_lock'                 => 0,
				'acfe_flexible_modal_edition'        => 0,
				'acfe_flexible_modal'                => [
					'acfe_flexible_modal_enabled'    => false,
					'acfe_flexible_modal_title'      => false,
					'acfe_flexible_modal_col'        => '4',
					'acfe_flexible_modal_categories' => false,
				],
				'acfe_flexible_layouts_state'           => '',
				'acfe_flexible_layouts_remove_collapse' => 0,
				'key'               => 'field_5e459a7309ba7',
				'label'             => __( 'Sections', 'affp-theme' ),
				'name'              => 'front_page_sections',
				'type'              => 'flexible_content',
				'instructions'      => __( '', 'affp-theme' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'layouts' => [
					'layout_5e459d90ee518' => [
						'key'        => 'layout_5e459d90ee518',
						'name'       => 'fp_section_content',
						'label'      => __( 'Standard Content Editor', 'affp-theme' ),
						'display'    => 'row',
						'sub_fields' => [
							[
								'key'               => 'field_5e459ec1957fe',
								'label'             => __( 'Section Title', 'affp-theme' ),
								'name'              => 'fp_section_title',
								'type'              => 'text',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e459ed2957ff',
								'label'             => __( 'Section Slug', 'affp-theme' ),
								'name'              => 'fp_section_slug',
								'type'              => 'text',
								'instructions'      => __( 'Lowercase. Used for scrolling and for the section hashtag in the URL.', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e459dc0957fd',
								'label'             => __( 'Section Content', 'affp-theme' ),
								'name'              => 'fp_section_content_editor',
								'type'              => 'wysiwyg',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'tabs'              => 'all',
								'toolbar'           => 'full',
								'media_upload'      => 1,
								'delay'             => 0,
							],
							[
								'key'               => 'field_5e46dd65d1fe0',
								'label'             => __( 'Section Link', 'affp-theme' ),
								'name'              => 'fp_section_link_slug',
								'type'              => 'text',
								'instructions'      => __( 'Optional. Enter the lowercase slug of the section to which this will link.', 'affp-theme' ),
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e46ddf2d1fe1',
								'label'             => __( 'Section Link Text', 'affp-theme' ),
								'name'              => 'fp_section_link_text',
								'type'              => 'text',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => [
									[
										[
											'field'    => 'field_5e46dd65d1fe0',
											'operator' => '!=empty',
										],
									],
								],
								'wrapper' => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e46de33d1fe2',
								'label'             => __( 'Section Link Icon', 'affp-theme' ),
								'name'              => 'fp_section_link_icon',
								'type'              => 'button_group',
								'instructions'      => __( 'Choose an up or down indicator for this link.', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => [
									[
										[
											'field'    => 'field_5e46dd65d1fe0',
											'operator' => '!=empty',
										],
									],
								],
								'wrapper' => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'acfe_permissions' => '',
								'choices'          => [
									'down'  => __( 'Down', 'affp-theme' ),
									'up'    => __( 'Up', 'affp-theme' ),
									'right' => __( 'Right (new page)', 'affp-theme' ),
								],
								'allow_null'    => 0,
								'default_value' => 'down',
								'layout'        => 'horizontal',
								'return_format' => 'value',
							],
						],
						'min'                           => '',
						'max'                           => '',
						'acfe_flexible_thumbnail'       => false,
						'acfe_flexible_category'        => false,
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style'    => false,
						'acfe_flexible_render_script'   => false,
						'acfe_flexible_settings'        => false,
						'acfe_flexible_settings_size'   => 'medium',
					],
					'layout_5e45a05134f51' => [
						'key'        => 'layout_5e45a05134f51',
						'name'       => 'fp_section_projects',
						'label'      => __( 'Projects List', 'affp-theme' ),
						'display'    => 'row',
						'sub_fields' => [
							[
								'key'               => 'field_5e45a0fc81534',
								'label'             => __( 'Section Title', 'affp-theme' ),
								'name'              => 'fp_section_title',
								'type'              => 'text',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper' => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e45a13a87956',
								'label'             => __( 'Section Slug', 'affp-theme' ),
								'name'              => 'fp_section_slug',
								'type'              => 'text',
								'instructions'      => __( 'Lowercase. Used for scrolling and for the section hashtag in the URL.', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e45a2cf1ef62',
								'label'             => __( 'Presentaion', 'affp-theme' ),
								'name'              => 'fp_section_projects_display',
								'type'              => 'button_group',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'choices'           => [
									'slide' => __( 'Carousel', 'affp-theme' ),
									'grid'  => __( 'Grid', 'affp-theme' ),
								],
								'allow_null'        => 0,
								'default_value'     => '',
								'layout'            => 'horizontal',
								'return_format'     => 'value',
							],
							[
								'key'               => 'field_5e45a37d7c48b',
								'label'             => __( 'Projects', 'affp-theme' ),
								'name'              => 'fp_section_projects_list',
								'type'              => 'repeater',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'collapsed'         => 'field_5e45a3a37c48c',
								'min'               => 0,
								'max'               => 0,
								'layout'            => 'table',
								'button_label'      => __( 'Add Project', 'affp-theme' ),
								'sub_fields'        => [
									[
										'key'               => 'field_5e45a3a37c48c',
										'label'             => __( 'Project', 'affp-theme' ),
										'name'              => 'fp_section_projects_id',
										'type'              => 'post_object',
										'instructions'      => __( '', 'affp-theme' ),
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => [
											'width' => '',
											'class' => '',
											'id'    => '',
										],
										'post_type'         => [
											0 => 'project',
										],
										'taxonomy'          => '',
										'allow_null'        => 0,
										'multiple'          => 0,
										'return_format'     => 'object',
										'ui'                => 1,
									],
								],
							],
							[
								'key'               => 'field_5e46ded185ad3',
								'label'             => __( 'Section Link', 'affp-theme' ),
								'name'              => 'fp_section_link_slug',
								'type'              => 'text',
								'instructions'      => __( 'Optional. Enter the lowercase slug of the section to which this will link.', 'affp-theme' ),
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e46deee85ad4',
								'label'             => __( 'Section Link Text', 'affp-theme' ),
								'name'              => 'fp_section_link_text',
								'type'              => 'text',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => [
									[
										[
											'field'    => 'field_5e46dd65d1fe0',
											'operator' => '!=empty',
										],
									],
								],
								'wrapper' => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e46def985ad5',
								'label'             => __( 'Section Link Icon', 'affp-theme' ),
								'name'              => 'fp_section_link_icon',
								'type'              => 'button_group',
								'instructions'      => __( 'Choose an up or down indicator for this link.', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => [
									[
										[
											'field'    => 'field_5e46dd65d1fe0',
											'operator' => '!=empty',
										],
									],
								],
								'wrapper' => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'acfe_permissions' => '',
								'choices'          => [
									'down'  => __( 'Down', 'affp-theme' ),
									'up'    => __( 'Up', 'affp-theme' ),
									'right' => __( 'Right (new page)', 'affp-theme' ),
								],
								'allow_null'    => 0,
								'default_value' => 'down',
								'layout'        => 'horizontal',
								'return_format' => 'value',
							],
						],
						'min' => '',
						'max' => '',
						'acfe_flexible_thumbnail'       => false,
						'acfe_flexible_category'        => false,
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style'    => false,
						'acfe_flexible_render_script'   => false,
						'acfe_flexible_settings'        => false,
						'acfe_flexible_settings_size'   => 'medium',
					],
					'layout_5e45a988a76b6' => [
						'key'        => 'layout_5e45a988a76b6',
						'name'       => 'fp_section_press',
						'label'      => __( 'Press Articles', 'affp-theme' ),
						'display'    => 'row',
						'sub_fields' => [
							[
								'key'               => 'field_5e45a988a76b7',
								'label'             => __( 'Section Title', 'affp-theme' ),
								'name'              => 'fp_section_title',
								'type'              => 'text',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e45a988a76b8',
								'label'             => __( 'Section Slug', 'affp-theme' ),
								'name'              => 'fp_section_slug',
								'type'              => 'text',
								'instructions'      => __( 'Lowercase. Used for scrolling and for the section hashtag in the URL.', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e45a988a76b9',
								'label'             => __( 'Presentaion', 'affp-theme' ),
								'name'              => 'fp_section_press_display',
								'type'              => 'button_group',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'choices' => [
									'slide' => __( 'Carousel', 'affp-theme' ),
									'grid'  => __( 'Grid', 'affp-theme' ),
								],
								'allow_null'        => 0,
								'default_value'     => '',
								'layout'            => 'horizontal',
								'return_format'     => 'value',
							],
							[
								'key'               => 'field_5e45a988a76ba',
								'label'             => __( 'Articles', 'affp-theme' ),
								'name'              => 'fp_section_press_list',
								'type'              => 'repeater',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'collapsed'         => 'field_5e45a3a37c48c',
								'min'               => 0,
								'max'               => 0,
								'layout'            => 'table',
								'button_label'      => __( 'Add Project', 'affp-theme' ),
								'sub_fields'        => [
									[
										'key'               => 'field_5e45a988a76bb',
										'label'             => __( 'Article', 'affp-theme' ),
										'name'              => 'fp_section_press_id',
										'type'              => 'post_object',
										'instructions'      => __( '', 'affp-theme' ),
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => [
											'width' => '',
											'class' => '',
											'id'    => '',
										],
										'post_type' => [
											0 => 'press',
										],
										'taxonomy'      => '',
										'allow_null'    => 0,
										'multiple'      => 0,
										'return_format' => 'object',
										'ui'            => 1,
									],
								],
							],
							[
								'key'               => 'field_5e46df4285ad6',
								'label'             => __( 'Section Link', 'affp-theme' ),
								'name'              => 'fp_section_link_slug',
								'type'              => 'text',
								'instructions'      => __( 'Optional. Enter the lowercase slug of the section to which this will link.', 'affp-theme' ),
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e46df4785ad7',
								'label'             => __( 'Section Link Text', 'affp-theme' ),
								'name'              => 'fp_section_link_text',
								'type'              => 'text',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => [
									[
										[
											'field'    => 'field_5e46dd65d1fe0',
											'operator' => '!=empty',
										],
									],
								],
								'wrapper' => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value' => '',
								'placeholder'   => __( '', 'affp-theme' ),
								'prepend'       => '',
								'append'        => '',
								'maxlength'     => '',
							],
							[
								'key'               => 'field_5e46df4d85ad8',
								'label'             => __( 'Section Link Icon', 'affp-theme' ),
								'name'              => 'fp_section_link_icon',
								'type'              => 'button_group',
								'instructions'      => __( 'Choose an up or down indicator for this link.', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => [
									[
										[
											'field'    => 'field_5e46dd65d1fe0',
											'operator' => '!=empty',
										],
									],
								],
								'wrapper' => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'acfe_permissions' => '',
								'choices'          => [
									'down'  => __( 'Down', 'affp-theme' ),
									'up'    => __( 'Up', 'affp-theme' ),
									'right' => __( 'Right (new page)', 'affp-theme' ),
								],
								'allow_null'    => 0,
								'default_value' => 'down',
								'layout'        => 'horizontal',
								'return_format' => 'value',
							],
						],
						'min' => '',
						'max' => '',
						'acfe_flexible_thumbnail'       => false,
						'acfe_flexible_category'        => false,
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style'    => false,
						'acfe_flexible_render_script'   => false,
						'acfe_flexible_settings'        => false,
						'acfe_flexible_settings_size'   => 'medium',
					],
					'layout_5e461dc311722' => [
						'key'        => 'layout_5e461dc311722',
						'name'       => 'fp_section_page',
						'label'      => __( 'Existing Page', 'affp-theme' ),
						'display'    => 'row',
						'sub_fields' => [
							[
								'key'               => 'field_5e465c6f905a8',
								'label'             => __( 'Section Title', 'affp-theme' ),
								'name'              => 'fp_section_title',
								'type'              => 'text',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e465535ac281',
								'label'             => __( 'Section Slug', 'affp-theme' ),
								'name'              => 'fp_section_slug',
								'type'              => 'text',
								'instructions'      => __( 'Lowercase. Used for scrolling and for the section hashtag in the URL.', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => __( '', 'affp-theme' ),
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
							],
							[
								'key'               => 'field_5e461df411723',
								'label'             => __( 'Page', 'affp-theme' ),
								'name'              => 'fp_section_page_object',
								'type'              => 'post_object',
								'instructions'      => __( 'Make sure to select a page that has been assigned the "Single Front Page Section" template.', 'affp-theme' ),
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'post_type'     => [
									0 => 'page',
								],
								'taxonomy'      => '',
								'allow_null'    => 0,
								'multiple'      => 0,
								'return_format' => 'id',
								'ui'            => 1,
							],
							[
								'key'               => 'field_5e46dfae85ad9',
								'label'             => __( 'Section Link', 'affp-theme' ),
								'name'              => 'fp_section_link_slug',
								'type'              => 'text',
								'instructions'      => __( 'Optional. Enter the lowercase slug of the section to which this will link.', 'affp-theme' ),
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'      => '',
								'placeholder'        => __( '', 'affp-theme' ),
								'prepend'            => '',
								'append'             => '',
								'maxlength'          => '',
							],
							[
								'key'               => 'field_5e46dfd285ada',
								'label'             => __( 'Section Link Text', 'affp-theme' ),
								'name'              => 'fp_section_link_text',
								'type'              => 'text',
								'instructions'      => __( '', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => [
									[
										[
											'field'    => 'field_5e46dd65d1fe0',
											'operator' => '!=empty',
										],
									],
								],
								'wrapper' => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value' => '',
								'placeholder'   => __( '', 'affp-theme' ),
								'prepend'       => '',
								'append'        => '',
								'maxlength'     => '',
							],
							[
								'key'               => 'field_5e46dfd785adb',
								'label'             => __( 'Section Link Icon', 'affp-theme' ),
								'name'              => 'fp_section_link_icon',
								'type'              => 'button_group',
								'instructions'      => __( 'Choose an up or down indicator for this link.', 'affp-theme' ),
								'required'          => 1,
								'conditional_logic' => [
									[
										[
											'field'    => 'field_5e46dd65d1fe0',
											'operator' => '!=empty',
										],
									],
								],
								'wrapper' => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'acfe_permissions' => '',
								'choices'          => [
									'down'  => __( 'Down', 'affp-theme' ),
									'up'    => __( 'Up', 'affp-theme' ),
									'right' => __( 'Right (new page)', 'affp-theme' ),
								],
								'allow_null'    => 0,
								'default_value' => 'down',
								'layout'        => 'horizontal',
								'return_format' => 'value',
							],
						],
						'min' => '',
						'max' => '',
						'acfe_flexible_thumbnail'       => false,
						'acfe_flexible_category'        => false,
						'acfe_flexible_render_template' => false,
						'acfe_flexible_render_style'    => false,
						'acfe_flexible_render_script'   => false,
						'acfe_flexible_settings'        => false,
						'acfe_flexible_settings_size'   => 'medium',
					],
				],
				'button_label' => __( 'Add Section', 'affp-theme' ),
				'min'          => 1,
				'max'          => '',
			],
		],
		'location' => [
			[
				[
					'param'    => 'page_type',
					'operator' => '==',
					'value'    => 'front_page',
				],
				[
					'param'    => 'page_template',
					'operator' => '==',
					'value'    => 'page-templates/front-page-sections.php',
				],
			],
		],
		'menu_order'            => 0,
		'position'              => 'acf_after_title',
		'style'                 => 'seamless',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => [
			0  => 'the_content',
			1  => 'excerpt',
			2  => 'discussion',
			3  => 'comments',
			4  => 'revisions',
			5  => 'slug',
			6  => 'author',
			7  => 'format',
			8  => 'categories',
			9  => 'tags',
			10 => 'send-trackbacks',
		],
		'active'             => true,
		'description'        => __( '', 'affp-theme' ),
		'acfe_display_title' => '',
		'acfe_autosync'      => '',
		'acfe_permissions'   => '',
		'acfe_form'          => 0,
		'acfe_meta'          => '',
		'acfe_note'          => '',
	] );

endif;